### ISSUE TITLE
Todo for Api Initial Spec

### ISSUE THREAD

**Issue by bennycio** [gallery-so/go-gallery#62]
**TODO**

- [x] auth endpoints are done but make sure they are still functional with all of the other changes made to the code base
- [x] get user endpoints returning different results for auth vs un-auth
- [x] get collections endpoints returning different results for auth vs un-auth
- [x] collection update endpoint
- [x] ensure sync endpoint has no blindspots
- [x] delete collection endpoint
- [ ] test endpoints with integration tests
